config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  get 'products/index'
  get 'products/new'
  get 'products/edit'
  root 'products#index'
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :products
  resources :orders

end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items
  
    # LOGIC
    def sub_total
      sum = 0
      line_items.each do |line_item|
        sum+= line_item.total_price
      end
      sum
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :intialize_Cart_Object, only: %i[show destroy]

  def destroy
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
    
  private 
  def intialize_Cart_Object
    @cart = @current_cart
  end
end

app/views/carts/show.html.erb
<h2>Cart show</h2>
 <%# <%= link_to "Add one", line_item_add_path(:id => 7), method: :post %> 
<ul>
  <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.product.name %><br> 
    Price: <%= number_to_currency(line_item.product.price) %><br>
    Quantity: <%= line_item.quantity %><br>
    Total Price: <%= number_to_currency(line_item.total_price) %>
    
    <ul>
      <li>
        <%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
        <%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
      </li>
    </ul>
    
  <% end %>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
<%= link_to "Proceed to checkout", new_order_path %><br>

<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} %><br>
<%= link_to "Home Page", root_path %>