config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  get 'products/index'
  get 'products/new'
  get 'products/edit'
  root 'products#index'
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :products
  resources :orders

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :line_items, dependent: :destroy
    validates :name, :price, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: %i[ edit update destroy]
  before_action :build_product, only: %i[new create]

  def index
    @products = Product.all
  end

  def create
    @product.assign_attributes(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :price)
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def build_product
    @product = Product.new
  end
end

app/views/products/_errors.html.erb
<% if @product.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/products/_errorshow.html.erb
<% if @product.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/products/edit.html.erb
<%= form_for(@product) do |f| %>
  <%= render "errors"%>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true, placeholder: "Enter product name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/index.html.erb
<h2>All Products</h2>
<% @products.each do |product| %>
  <p>Name: <%= product.name %>; unit price of <%= number_to_currency(product.price) %></p>
  <p>
    <%= link_to "Edit", edit_product_path(product) %> |
    <%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
    <%= button_to "Add #{product.name} to cart", line_items_path(:product_id => product.id) %>
  </p>
<% end%>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<%= form_for(@product) do |f| %>
 <%= render "errors"%>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true, placeholder: "Enter product name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end%>